version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80"
  db:
    image: mysql:8
    volumes:
      - "mysql_db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: daw_dsw
      MY_SQL_DATABASE: daw_dsw
      MY_SQL_USER: dsw
      MY_SQL_PASSWORD: dsw
volumes:
  mysql_db: