version: "3.9"
services:
  dsw:
    build: ./dsw
    volumes:
      - "./dsw/src:/var/www/html"
    ports:
      - "8080:80"

  db:
    build: ./db
    volumes:
      - "dsw_mysql_db:/var/lib/mysql"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: dsw
      MYSQL_DATABASE: commercedb
      MYSQL_USER: dsw
      MYSQL_PASSWORD: dsw
  adminer:
    image: adminer
    ports:
      - "8090:8080"
      
volumes:
  dsw_mysql_db: